**motivation**<br>
Paul Davies wrote a piece for the 2018 summer special edition of the <i>Scientific American</i>, titled "That Mysterious Flow", where he gave an example of special relativity (screenshots in below cell). The goal of this notebook is to replicate the results in his example.

<img src="davies_1.png" width="600" height="600" />         

<img src="davies_2.png" width="600" height="600" />         

In [1]:
import numpy as np

**from Lorentz tranformation we define the following functions:**<br>
**L(x, t, v, c)** returns location and time of what's deemed moving <br/>
**f(x_prime, t, v, c)** returns location of what's deemed stationary, and time of what's deemed moving <br/>
**g(x, x_prime, v, c)** returns time of what's deemed stationary, and time of what's deemed moving <br/>
**h(t, t_prime, v, c)** returns location of what's deemed stationary, and location of what's deemed moving

In [2]:
def L(x, t, v, c):
    '''x: location coordinate of what's deemed stationary
       t: time coordinate of what's deemed stationary
       v: speed of what's deemed moving, including direction 
       c: speed of light
       return: location and time of what's deemed moving
       in the train/platform example, if v > 0, then (x, t) is platform; if v < 0, then (x, t) is train'''
    root = (1-(v**2/c**2))**0.5
    x_prime = (x - v*t)/root
    t_prime = (t - (v/c**2)*x)/root
    return np.array([x_prime, t_prime])

In [3]:
def f(x_prime, t, v, c):
    '''here the cross coordinates are given, either (train location, platform time) or (platform location, train time)
       x_prime: location coordinate of what's deemed moving
       t: time coordinate of what's deemed stationary
       v: speed of what's deemed moving, including direction (if v > 0, train is prime; if v < 0, platform is prime)
       c: speed of light
       return: location of what's deemed stationary, and time of what's deemed moving
       '''
    root = (1-(v**2/c**2))**0.5
    x = root * x_prime + v*t
    t_prime = (t - (v/c**2)*x)/root
    return np.array([x, t_prime])

In [4]:
def g(x, x_prime, v, c):
    '''
    x: location coordinate of what's deemed stationary
    x_prime: location coordinate of what's deemed moving
    v: speed of what's deemed moving, including direction (if v > 0, train is prime; if v < 0, platform is prime)
    c: speed of light
    return: time of what's deemed stationary, and time of what's deemed moving
    '''
    root = (1-(v**2/c**2))**0.5
    t = (x/v) - (x_prime/v)*root
    t_prime = (t - (v/c**2)*x)/root
    return np.array([t, t_prime])

In [5]:
def h(t, t_prime, v, c):
    '''
    t: time coordinate of what's deemed stationary
    t_prime: time coordinate of what's deemed moving
    v: speed of what's deemed moving, including direction (if v > 0, train is prime; if v < 0, platform is prime)
    c: speed of light  
    return: location of what's deemed stationary, and location of what's deemed moving
    '''
    root = (1-(v**2/c**2))**0.5
    x = (c**2/v)*t - (c**2/v)*t_prime*root
    x_prime = (x - v*t)/root
    return np.array([x, x_prime])

In Davies's example, let the unit of time be minute, and the unit of distance be light minute (i.e. the distance covered by light in one minute). So $c$ = 1, and $v$ = 0.8. If we deem rocket as moving, then $v$ = 0.8; if we deem earth-mars as moving, then $v$ = -0.8. We also normalize 12:00PM in the example to be 0, so for example, $t$ = 12:15PM would be $t$ = 15 in our formulation.

## As seen from earth

**12:00pm - the martian sends a signal to the earthling.**

**12:11pm - knowing the rocket’s speed, the earthling deduces that it encounters the signal while on its way to Mars.**

In [6]:
# from earthling's perspective, when does the rocket receive the signal?
# let the time when rocket receives the signal be t, then t*v + t*c = 20, t = 20/(v + c)
v = 0.8
c = 1
t = 20/1.8 # approximately 11 minutes after noon
t

11.11111111111111

**12:20pm - the signal arrives at Earth. The earthling has confirmed his earlier hypothesis. Noon on Mars is the same as noon on Earth.**

**12:25pm - The ship arrives at Mars. The ship is traveling at 80% the speed of light, so what takes light 20 minutes takes the ship 25.**

## As seen from the rocket

**the distance between earth and mars, as measured by the rocket is 12 minutes**

In [7]:
# rocket deemed stationary, earth-mars move leftwards
f(0,0,-0.8,1), f(20,0,-0.8,1), f(20,0,-0.8,1)[0] - f(0,0,-0.8,1)[0] 

(array([0., 0.]), array([12., 16.]), 11.999999999999996)

**12:00pm - passing Earth, the rocket man hypothesizes that the Martian has begun to eat. He prepares to wait 12 minutes for verification.** <br>
Here the assumption is that the rocket man doesn't know special relativity! He naively assumes that when his watch is 12:00pm, so is the martian's watch 12 light minutes away. As shown in the below cell, the martian's watch is actually pointing to 12:16pm!

In [8]:
L(12, 0, -0.8, 1)

array([20., 16.])

**12:07pm - the signal arrives, disproving the hypothesis. The rocket man infers that the Martian ate sometime before noon (rocket time).**

In [9]:
# from earthling's perspective, when does the rocket receives the signal?
# let the time when rocket receives the signal be t, then t*v + t*c = 20, t = 20/(v + c)
v = 0.8
c = 1
t = 20/1.8 # approximately 11 minutes after noon

# from earthling's perspective, where does the rocket receive the signal?
x = t*v

# taking (x, t) from the calculation in this cell, applying Lorentz transformation, we have
L(x, t, 0.8, 1) # approximately 7 minutes rocket time

array([0.        , 6.66666667])

**12:15pm - rocket arrives at mars**

In [10]:
# 12:15 - rocket arrives at Mars, this means that rocket origin coincides with mars, whose location is 20 in the earth
# mars frame; notice that the earthling believes that rocket arrives at Mars at 12:25
g(0, 20, -0.8, 1)

array([15., 25.])

**12:33pm - signal from mars arrives at earth according to rocket time**

In [11]:
# 12:33 - signal arrives at earth
# when signal arrives at earth, earth records this as (0, 20), because the origin receives the signal traveling 20 min
# after noon, translate this into rocket coordinates, we have
L(0, 20, 0.8, 1)

array([-26.66666667,  33.33333333])

**discussion**<br>
Did you notice something strange? To the earthling, the signal arrives at earth at 12:20, and then the ship arrives at Mars at 12:25; to the rocket man, the ship arrives at Mars at 12:15, and then the signal arrives at earth at 12:33. The earthling thinks that the signal arrives at earth before the ship arrives at Mars, but the rocket man thinks the opposite! Earth and Rocket have their own judgment on simultaneity, one consequence of which is that things may not happen in the same order!<br>

When the signal arrives at earth, you ask the earthling: does the ship arrive at Mars yet? He looks at his watch and says not yet; when the ship does arrive at Mars, you ask the rocket man: does the signal arrive at earth yet? He looks at <i>his</i> watch and says not yet! It seems that Earthling's future (ship arrives at Mars) is rocket man's past; earthling's past (signal arrives at earth) is rocket man's future!